-- Pywal Theme Definition
-- Reads colors from ~/.cache/wal/colors.json (generated by pywal16)
-- Falls back to terminal colors when no explicit colorscheme is set

local M = {}

M.icon = ""
M.variants = { "dark", "light" }

-- Cache file path
local colors_file = vim.fn.expand("~/.cache/wal/colors.json")

-- Load colors from pywal JSON
local function load_pywal_colors()
  if vim.fn.filereadable(colors_file) ~= 1 then
    return nil
  end

  local ok, content = pcall(vim.fn.readfile, colors_file)
  if not ok or not content[1] then
    return nil
  end

  local success, data = pcall(vim.json.decode, table.concat(content, "\n"))
  if not success or not data then
    return nil
  end

  return data
end

-- Determine if a color is "light" (for auto-detection)
local function is_light_color(hex)
  if not hex or not hex:match("^#%x%x%x%x%x%x$") then
    return false
  end
  local r = tonumber(hex:sub(2, 3), 16)
  local g = tonumber(hex:sub(4, 5), 16)
  local b = tonumber(hex:sub(6, 7), 16)
  -- Relative luminance formula
  local luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255
  return luminance > 0.5
end

-- Blend two colors
local function blend(fg, bg, alpha)
  if not fg or not bg then
    return fg or bg
  end

  local function hex_to_rgb(hex)
    return tonumber(hex:sub(2, 3), 16), tonumber(hex:sub(4, 5), 16), tonumber(hex:sub(6, 7), 16)
  end

  local r1, g1, b1 = hex_to_rgb(fg)
  local r2, g2, b2 = hex_to_rgb(bg)

  local r = math.floor(r1 * alpha + r2 * (1 - alpha))
  local g = math.floor(g1 * alpha + g2 * (1 - alpha))
  local b = math.floor(b1 * alpha + b2 * (1 - alpha))

  return string.format("#%02x%02x%02x", r, g, b)
end

-- Darken a color
local function darken(hex, amount)
  if not hex then
    return hex
  end
  return blend("#000000", hex, amount)
end

-- Lighten a color
local function lighten(hex, amount)
  if not hex then
    return hex
  end
  return blend("#ffffff", hex, amount)
end

-- Apply highlight groups
local function apply_highlights(colors, transparent)
  local bg = colors.special.background
  local fg = colors.special.foreground
  local cursor = colors.special.cursor
  local c = colors.colors

  -- Helper for creating subtle variations
  local bg_dark = darken(bg, 0.2)
  local bg_light = lighten(bg, 0.15)
  local bg_lighter = lighten(bg, 0.25)
  local fg_dim = blend(fg, bg, 0.6)
  local fg_dimmer = blend(fg, bg, 0.4)

  -- Transparent background
  local actual_bg = transparent and "NONE" or bg

  -- Core highlight groups
  local highlights = {
    -- Editor
    Normal = { fg = fg, bg = actual_bg },
    NormalNC = { fg = fg, bg = actual_bg },
    NormalFloat = { fg = fg, bg = transparent and "NONE" or bg_light },
    FloatBorder = { fg = c.color8, bg = transparent and "NONE" or bg_light },
    FloatTitle = { fg = c.color4, bg = transparent and "NONE" or bg_light, bold = true },
    Cursor = { fg = bg, bg = cursor },
    CursorLine = { bg = transparent and "NONE" or bg_light },
    CursorColumn = { bg = bg_light },
    ColorColumn = { bg = bg_light },
    LineNr = { fg = c.color8 },
    CursorLineNr = { fg = c.color4, bold = true },
    SignColumn = { fg = fg, bg = actual_bg },
    VertSplit = { fg = c.color8 },
    WinSeparator = { fg = c.color8 },
    Folded = { fg = c.color8, bg = bg_light },
    FoldColumn = { fg = c.color8, bg = actual_bg },
    EndOfBuffer = { fg = bg },
    NonText = { fg = c.color8 },
    SpecialKey = { fg = c.color8 },
    Conceal = { fg = c.color8 },
    MatchParen = { fg = c.color6, bold = true, underline = true },

    -- Pmenu (completion menu)
    Pmenu = { fg = fg, bg = bg_light },
    PmenuSel = { fg = bg, bg = c.color4, bold = true },
    PmenuSbar = { bg = bg_lighter },
    PmenuThumb = { bg = c.color8 },

    -- Search
    Search = { fg = bg, bg = c.color3 },
    IncSearch = { fg = bg, bg = c.color4, bold = true },
    CurSearch = { fg = bg, bg = c.color6, bold = true },
    Substitute = { fg = bg, bg = c.color1 },

    -- Visual
    Visual = { bg = blend(c.color4, bg, 0.3) },
    VisualNOS = { bg = blend(c.color4, bg, 0.2) },

    -- Statusline
    StatusLine = { fg = fg, bg = bg_light },
    StatusLineNC = { fg = fg_dim, bg = bg_dark },
    WinBar = { fg = fg, bg = actual_bg },
    WinBarNC = { fg = fg_dim, bg = actual_bg },

    -- Tabline
    TabLine = { fg = fg_dim, bg = bg_dark },
    TabLineFill = { bg = bg_dark },
    TabLineSel = { fg = fg, bg = actual_bg, bold = true },

    -- Messages
    ModeMsg = { fg = c.color2, bold = true },
    MsgArea = { fg = fg },
    MoreMsg = { fg = c.color2 },
    Question = { fg = c.color4 },
    ErrorMsg = { fg = c.color1, bold = true },
    WarningMsg = { fg = c.color3 },

    -- Diff
    DiffAdd = { bg = blend(c.color2, bg, 0.2) },
    DiffChange = { bg = blend(c.color4, bg, 0.2) },
    DiffDelete = { fg = c.color1, bg = blend(c.color1, bg, 0.1) },
    DiffText = { bg = blend(c.color4, bg, 0.4) },

    -- Spell
    SpellBad = { undercurl = true, sp = c.color1 },
    SpellCap = { undercurl = true, sp = c.color3 },
    SpellLocal = { undercurl = true, sp = c.color4 },
    SpellRare = { undercurl = true, sp = c.color5 },

    -- Syntax
    Comment = { fg = c.color8, italic = true },
    Constant = { fg = c.color5 },
    String = { fg = c.color2 },
    Character = { fg = c.color2 },
    Number = { fg = c.color5 },
    Boolean = { fg = c.color5 },
    Float = { fg = c.color5 },

    Identifier = { fg = c.color4 },
    Function = { fg = c.color4, bold = true },

    Statement = { fg = c.color1 },
    Conditional = { fg = c.color1 },
    Repeat = { fg = c.color1 },
    Label = { fg = c.color1 },
    Operator = { fg = fg },
    Keyword = { fg = c.color5, italic = true },
    Exception = { fg = c.color1 },

    PreProc = { fg = c.color6 },
    Include = { fg = c.color6 },
    Define = { fg = c.color6 },
    Macro = { fg = c.color6 },
    PreCondit = { fg = c.color6 },

    Type = { fg = c.color3 },
    StorageClass = { fg = c.color3 },
    Structure = { fg = c.color3 },
    Typedef = { fg = c.color3 },

    Special = { fg = c.color6 },
    SpecialChar = { fg = c.color6 },
    Tag = { fg = c.color4 },
    Delimiter = { fg = fg },
    SpecialComment = { fg = c.color8, italic = true },
    Debug = { fg = c.color1 },

    Underlined = { fg = c.color4, underline = true },
    Ignore = { fg = c.color8 },
    Error = { fg = c.color1, bold = true },
    Todo = { fg = bg, bg = c.color3, bold = true },

    -- Diagnostics
    DiagnosticError = { fg = c.color1 },
    DiagnosticWarn = { fg = c.color3 },
    DiagnosticInfo = { fg = c.color4 },
    DiagnosticHint = { fg = c.color6 },
    DiagnosticOk = { fg = c.color2 },

    DiagnosticUnderlineError = { undercurl = true, sp = c.color1 },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.color3 },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.color4 },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.color6 },
    DiagnosticUnderlineOk = { undercurl = true, sp = c.color2 },

    DiagnosticVirtualTextError = { fg = c.color1, bg = blend(c.color1, bg, 0.1) },
    DiagnosticVirtualTextWarn = { fg = c.color3, bg = blend(c.color3, bg, 0.1) },
    DiagnosticVirtualTextInfo = { fg = c.color4, bg = blend(c.color4, bg, 0.1) },
    DiagnosticVirtualTextHint = { fg = c.color6, bg = blend(c.color6, bg, 0.1) },
    DiagnosticVirtualTextOk = { fg = c.color2, bg = blend(c.color2, bg, 0.1) },

    DiagnosticSignError = { fg = c.color1 },
    DiagnosticSignWarn = { fg = c.color3 },
    DiagnosticSignInfo = { fg = c.color4 },
    DiagnosticSignHint = { fg = c.color6 },
    DiagnosticSignOk = { fg = c.color2 },

    -- LSP
    LspReferenceText = { bg = bg_lighter },
    LspReferenceRead = { bg = bg_lighter },
    LspReferenceWrite = { bg = bg_lighter },
    LspSignatureActiveParameter = { fg = c.color4, bold = true },
    LspCodeLens = { fg = c.color8 },
    LspInlayHint = { fg = fg_dimmer, bg = blend(c.color8, bg, 0.1) },

    -- Treesitter
    ["@variable"] = { fg = fg },
    ["@variable.builtin"] = { fg = c.color1, italic = true },
    ["@variable.parameter"] = { fg = c.color6 },
    ["@variable.member"] = { fg = c.color4 },

    ["@constant"] = { fg = c.color5 },
    ["@constant.builtin"] = { fg = c.color5, bold = true },
    ["@constant.macro"] = { fg = c.color5 },

    ["@module"] = { fg = c.color3 },
    ["@label"] = { fg = c.color1 },

    ["@string"] = { fg = c.color2 },
    ["@string.documentation"] = { fg = c.color2 },
    ["@string.regexp"] = { fg = c.color6 },
    ["@string.escape"] = { fg = c.color6, bold = true },
    ["@string.special"] = { fg = c.color6 },

    ["@character"] = { fg = c.color2 },
    ["@character.special"] = { fg = c.color6 },

    ["@boolean"] = { fg = c.color5 },
    ["@number"] = { fg = c.color5 },
    ["@number.float"] = { fg = c.color5 },

    ["@type"] = { fg = c.color3 },
    ["@type.builtin"] = { fg = c.color3, italic = true },
    ["@type.definition"] = { fg = c.color3 },

    ["@attribute"] = { fg = c.color6 },
    ["@property"] = { fg = c.color4 },

    ["@function"] = { fg = c.color4, bold = true },
    ["@function.builtin"] = { fg = c.color4 },
    ["@function.call"] = { fg = c.color4 },
    ["@function.macro"] = { fg = c.color6 },
    ["@function.method"] = { fg = c.color4 },
    ["@function.method.call"] = { fg = c.color4 },

    ["@constructor"] = { fg = c.color3 },

    ["@operator"] = { fg = fg },

    ["@keyword"] = { fg = c.color5, italic = true },
    ["@keyword.coroutine"] = { fg = c.color5, italic = true },
    ["@keyword.function"] = { fg = c.color5, italic = true },
    ["@keyword.operator"] = { fg = c.color5 },
    ["@keyword.import"] = { fg = c.color6 },
    ["@keyword.storage"] = { fg = c.color5 },
    ["@keyword.repeat"] = { fg = c.color1 },
    ["@keyword.return"] = { fg = c.color1 },
    ["@keyword.exception"] = { fg = c.color1 },
    ["@keyword.conditional"] = { fg = c.color1 },

    ["@punctuation.delimiter"] = { fg = fg },
    ["@punctuation.bracket"] = { fg = fg },
    ["@punctuation.special"] = { fg = c.color6 },

    ["@comment"] = { fg = c.color8, italic = true },
    ["@comment.documentation"] = { fg = c.color8 },
    ["@comment.error"] = { fg = c.color1, bg = blend(c.color1, bg, 0.1) },
    ["@comment.warning"] = { fg = c.color3, bg = blend(c.color3, bg, 0.1) },
    ["@comment.todo"] = { fg = bg, bg = c.color4 },
    ["@comment.note"] = { fg = bg, bg = c.color6 },

    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.color4, bold = true },
    ["@markup.quote"] = { fg = fg_dim, italic = true },
    ["@markup.math"] = { fg = c.color6 },
    ["@markup.link"] = { fg = c.color4 },
    ["@markup.link.label"] = { fg = c.color4, underline = true },
    ["@markup.link.url"] = { fg = c.color6, underline = true },
    ["@markup.raw"] = { fg = c.color2 },
    ["@markup.list"] = { fg = c.color4 },

    ["@tag"] = { fg = c.color1 },
    ["@tag.attribute"] = { fg = c.color4 },
    ["@tag.delimiter"] = { fg = fg_dim },

    -- Git signs
    GitSignsAdd = { fg = c.color2 },
    GitSignsChange = { fg = c.color4 },
    GitSignsDelete = { fg = c.color1 },

    -- Telescope
    TelescopeBorder = { fg = c.color8, bg = transparent and "NONE" or bg },
    TelescopeNormal = { fg = fg, bg = transparent and "NONE" or bg },
    TelescopePromptBorder = { fg = c.color4, bg = transparent and "NONE" or bg },
    TelescopePromptTitle = { fg = bg, bg = c.color4 },
    TelescopePreviewTitle = { fg = bg, bg = c.color2 },
    TelescopeResultsTitle = { fg = bg, bg = c.color6 },
    TelescopeSelection = { bg = bg_light },
    TelescopeSelectionCaret = { fg = c.color4 },
    TelescopeMatching = { fg = c.color6, bold = true },

    -- nvim-cmp
    CmpItemAbbrMatch = { fg = c.color4, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.color4 },
    CmpItemAbbrDeprecated = { fg = c.color8, strikethrough = true },
    CmpItemKind = { fg = c.color5 },
    CmpItemMenu = { fg = c.color8 },

    -- Which-key
    WhichKey = { fg = c.color4 },
    WhichKeyGroup = { fg = c.color5 },
    WhichKeyDesc = { fg = fg },
    WhichKeySeparator = { fg = c.color8 },
    WhichKeyValue = { fg = c.color8 },

    -- Lazy
    LazyButton = { fg = fg, bg = bg_light },
    LazyButtonActive = { fg = bg, bg = c.color4, bold = true },
    LazyH1 = { fg = bg, bg = c.color4, bold = true },
    LazySpecial = { fg = c.color6 },

    -- Mason
    MasonHeader = { fg = bg, bg = c.color4, bold = true },
    MasonHighlight = { fg = c.color4 },
    MasonHighlightBlock = { fg = bg, bg = c.color2 },
    MasonHighlightBlockBold = { fg = bg, bg = c.color2, bold = true },

    -- Neo-tree
    NeoTreeNormal = { fg = fg, bg = transparent and "NONE" or bg },
    NeoTreeNormalNC = { fg = fg, bg = transparent and "NONE" or bg },
    NeoTreeDirectoryName = { fg = c.color4 },
    NeoTreeDirectoryIcon = { fg = c.color4 },
    NeoTreeRootName = { fg = c.color4, bold = true },
    NeoTreeFileName = { fg = fg },
    NeoTreeFileIcon = { fg = fg },
    NeoTreeGitAdded = { fg = c.color2 },
    NeoTreeGitModified = { fg = c.color4 },
    NeoTreeGitDeleted = { fg = c.color1 },
    NeoTreeGitUntracked = { fg = c.color3 },
    NeoTreeIndentMarker = { fg = c.color8 },

    -- Notify
    NotifyERRORBorder = { fg = c.color1 },
    NotifyERRORIcon = { fg = c.color1 },
    NotifyERRORTitle = { fg = c.color1 },
    NotifyWARNBorder = { fg = c.color3 },
    NotifyWARNIcon = { fg = c.color3 },
    NotifyWARNTitle = { fg = c.color3 },
    NotifyINFOBorder = { fg = c.color4 },
    NotifyINFOIcon = { fg = c.color4 },
    NotifyINFOTitle = { fg = c.color4 },
    NotifyDEBUGBorder = { fg = c.color8 },
    NotifyDEBUGIcon = { fg = c.color8 },
    NotifyDEBUGTitle = { fg = c.color8 },
    NotifyTRACEBorder = { fg = c.color5 },
    NotifyTRACEIcon = { fg = c.color5 },
    NotifyTRACETitle = { fg = c.color5 },

    -- Indent blankline
    IblIndent = { fg = bg_lighter },
    IblScope = { fg = c.color4 },

    -- Mini
    MiniStatuslineModeNormal = { fg = bg, bg = c.color4, bold = true },
    MiniStatuslineModeInsert = { fg = bg, bg = c.color2, bold = true },
    MiniStatuslineModeVisual = { fg = bg, bg = c.color5, bold = true },
    MiniStatuslineModeReplace = { fg = bg, bg = c.color1, bold = true },
    MiniStatuslineModeCommand = { fg = bg, bg = c.color3, bold = true },
    MiniStatuslineModeOther = { fg = bg, bg = c.color6, bold = true },

    -- Snacks
    SnacksIndent = { fg = bg_lighter },
    SnacksIndentScope = { fg = c.color4 },
    SnacksDashboardHeader = { fg = c.color4 },
    SnacksDashboardIcon = { fg = c.color4 },
    SnacksDashboardKey = { fg = c.color5 },
    SnacksDashboardDesc = { fg = fg },
    SnacksDashboardFooter = { fg = c.color8 },
  }

  -- Clear existing highlights
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
  end

  -- Apply all highlights
  for group, attrs in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, attrs)
  end

  -- Set terminal colors
  vim.g.terminal_color_0 = c.color0
  vim.g.terminal_color_1 = c.color1
  vim.g.terminal_color_2 = c.color2
  vim.g.terminal_color_3 = c.color3
  vim.g.terminal_color_4 = c.color4
  vim.g.terminal_color_5 = c.color5
  vim.g.terminal_color_6 = c.color6
  vim.g.terminal_color_7 = c.color7
  vim.g.terminal_color_8 = c.color8
  vim.g.terminal_color_9 = c.color9
  vim.g.terminal_color_10 = c.color10
  vim.g.terminal_color_11 = c.color11
  vim.g.terminal_color_12 = c.color12
  vim.g.terminal_color_13 = c.color13
  vim.g.terminal_color_14 = c.color14
  vim.g.terminal_color_15 = c.color15
end

-- Check if pywal colors are available
function M.is_available()
  return vim.fn.filereadable(colors_file) == 1
end

-- Get the colors (for external use)
function M.get_colors()
  return load_pywal_colors()
end

-- Setup function
function M.setup(opts)
  local colors = load_pywal_colors()
  if not colors then
    vim.notify("Pywal colors not found at " .. colors_file, vim.log.levels.WARN)
    return false
  end

  -- Determine background from variant or auto-detect
  local bg = opts.background
  if opts.variant == "light" then
    bg = "light"
  elseif opts.variant == "dark" then
    bg = "dark"
  elseif not bg then
    -- Auto-detect from pywal background color
    bg = is_light_color(colors.special.background) and "light" or "dark"
  end

  vim.o.background = bg

  -- Apply highlights
  apply_highlights(colors, opts.transparency)

  -- Set colorscheme name and trigger ColorScheme autocmd
  -- (other themes use vim.cmd("colorscheme ...") which triggers this automatically)
  vim.g.colors_name = "pywal"
  vim.api.nvim_exec_autocmds("ColorScheme", { pattern = "pywal" })

  return true
end

return M
